name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: linux/amd64     , exefile_name: "linux-amd64", extension: ""   }
          - { os: macos-latest   , target: darwin/arm64    , exefile_name: "darwin-arm64", extension: ""   }
          - { os: windows-latest , target: windows/amd64   , exefile_name: "windows-amd64", extension: .exe }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get Project Name
        shell: bash
        run: |
          echo "PROJECT_NAME=$(basename $(pwd))" >> $GITHUB_ENV

      - name: Build
        shell: bash
        run: |
          mkdir -p build/${{ matrix.job.target }}
          TARGET=${{ matrix.job.target }}
          GOOS=${TARGET%/*}  # OS部分を抽出
          GOARCH=${TARGET#*/}  # アーキテクチャ部分を抽出
          go build -o build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }}

      - name: Rename artifacts
        shell: bash
        run: |
          mv build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.job.exefile_name }}${{ matrix.job.extension }}}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.exefile_name }}${{ matrix.job.extension }}
