name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: linux/amd64     , extension: ""   }
          - { os: macos-latest   , target: darwin/arm64    , extension: ""   }
          - { os: windows-latest , target: windows/amd64   , extension: .exe }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get Project Name
        shell: bash
        run: |
          echo "PROJECT_NAME=$(basename $(pwd))" >> $GITHUB_ENV
          echo "Project name is set to: $PROJECT_NAME"

      - name: Build
        shell: bash
        run: |
          mkdir -p build/${{ matrix.job.target }}
          TARGET=${{ matrix.job.target }}
          GOOS=${TARGET%/*}  # '/'より前をGOOSに設定
          GOARCH=${TARGET#*/}  # '/'より後をGOARCHに設定
          echo "Building for GOOS=$GOOS, GOARCH=$GOARCH"
          go build -o build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }}
          echo "Build completed. Listing files:"
          ls -l build/${{ matrix.job.target }}  # ビルド結果を確認

      - name: Rename artifacts
        shell: bash
        run: |
          # ビルド成果物の存在を確認してリネーム
          ORIGINAL_FILE="build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }}"
          RENAMED_FILE="build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}"
          echo "Checking for file: $ORIGINAL_FILE"
          if [ -f "$ORIGINAL_FILE" ]; then
            echo "File found. Renaming to: $RENAMED_FILE"
            mv "$ORIGINAL_FILE" "$RENAMED_FILE"
          else
            echo "Error: Build artifact not found at $ORIGINAL_FILE"
            exit 1
          fi

      - name: Debug Build Artifacts
        shell: bash
        run: |
          # リネーム後のファイルを確認
          echo "Contents of build directory after rename:"
          find build

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
