name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: linux/amd64     , extension: ""   }
          - { os: macos-latest   , target: darwin/arm64    , extension: ""   }
          - { os: windows-latest , target: windows/amd64   , extension: .exe }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # 必要なGoのバージョンを指定

      - name: Get Project Name
        shell: bash
        run: |
          # プロジェクト名を現在のディレクトリ名から取得
          echo "PROJECT_NAME=$(basename $(pwd))" >> $GITHUB_ENV
          echo "Project name is set to: $PROJECT_NAME"

      - name: Build
        shell: bash
        run: |
          # ビルドディレクトリの準備
          mkdir -p build/${{ matrix.job.target }}
          # ターゲット情報を分離
          TARGET=${{ matrix.job.target }}
          GOOS=${TARGET%/*}  # '/'より前をGOOSに設定
          GOARCH=${TARGET#*/}  # '/'より後をGOARCHに設定
          echo "Building for GOOS=$GOOS, GOARCH=$GOARCH"
          # ビルドを実行
          go build -o build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }}
          # ビルドされたファイルを確認
          ls -l build/${{ matrix.job.target }}

      - name: Rename artifacts
        shell: bash
        run: |
          # ビルド成果物の存在を確認してリネーム
          if [ -f build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }} ]; then
            mv build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}${{ matrix.job.extension }} \
               build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}-v${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
          else
            echo "Error: Build artifact not found!"
            exit 1
          fi

      - name: Debug Build Artifacts
        shell: bash
        run: |
          # リネーム後のファイルを確認
          echo "Contents of build directory after rename:"
          find build

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/${{ matrix.job.target }}/${{ env.PROJECT_NAME }}-v${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
